include(CheckSymbolExists)

check_symbol_exists(DNSServiceCreateConnection "dns_sd.h" HAVE_DNSSD)

if (HAVE_DNSSD)
    target_sources(ultimate-gaming-client-lib PRIVATE dnssd.c)
else ()
    target_sources(ultimate-gaming-client-lib PRIVATE microdns.c)
    if (OS_WINDOWS)
        pkg_check_modules(MICRODNS REQUIRED microdns)
        target_link_libraries(ultimate-gaming-client-lib PUBLIC ${MICRODNS_LIBRARIES})
    endif ()
    set(BUILD_SHARED_LIBS ON)
    include(BuildMicrodns)
    target_link_libraries(ultimate-gaming-client-lib PUBLIC microdns)
    unset(BUILD_SHARED_LIBS)
endif ()
